/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Zhuier (https://sketchfab.com/Zhuier)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/oiiaioooooiai-cat-30d27bf7fb224849b76e208a6eccdb36
Title: Oiiaioooooiai Cat
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["0"]: THREE.Mesh;
  };
  materials: {
    Muchkin2: THREE.MeshStandardMaterial;
  };
};

type ActionName = "Take 001";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Cat(props: React.JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null) as React.RefObject<THREE.Group>;
  const { nodes, materials, animations } = useGLTF(
    "/oiiaioooooiai_cat.glb"
  ) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group) as unknown as {
    actions: GLTFActions;
  };
  useEffect(() => {
    actions["Take 001"].play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="191d233c94184f188ac4fad4b07dc182fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.05}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Muchkin1002">
                  <mesh
                    name="0"
                    castShadow
                    receiveShadow
                    geometry={nodes["0"].geometry}
                    material={materials.Muchkin2}
                    morphTargetDictionary={nodes["0"].morphTargetDictionary}
                    morphTargetInfluences={nodes["0"].morphTargetInfluences}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/oiiaioooooiai_cat.glb");
