/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh: THREE.Mesh
    Mesh_1: THREE.Mesh
    Main_body1: THREE.Mesh
    glass: THREE.Mesh
    Color_Flame: THREE.Mesh
    Color_Flame001: THREE.Mesh
  }
  materials: {
    aiStandardSurface3: THREE.MeshStandardMaterial
    flame: THREE.MeshStandardMaterial
    main: THREE.MeshStandardMaterial
    glass_mat: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/jet.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.161, 2.861, -8.372]} rotation={[-Math.PI, 0, 0]} scale={0.635}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh.geometry}
          material={materials.aiStandardSurface3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1.geometry}
          material={materials.flame}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Main_body1.geometry}
        material={materials.main}
        position={[0.164, -1.411, 4.13]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.107}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass.geometry}
        material={materials.glass_mat}
        position={[0.231, -1.411, 4.13]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.107}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Color_Flame.geometry}
        material={materials['Material.006']}
        position={[0.166, 2.483, -8.843]}
        rotation={[-2.826, 1.551, -1.886]}
        scale={[0.504, 4.389, 0.396]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Color_Flame001.geometry}
        material={materials['Material.002']}
        position={[0.166, 3.216, -8.868]}
        rotation={[-1.502, -1.485, -3.071]}
        scale={[0.365, 4.388, 0.397]}
      />
    </group>
  )
}

useGLTF.preload('/jet.glb')
