/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { PerspectiveCamera, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { ThreeElements } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder021: THREE.Mesh;
    Cylinder021_1: THREE.Mesh;
    Cylinder021_2: THREE.Mesh;
    Cylinder021_3: THREE.Mesh;
    Cylinder021_4: THREE.Mesh;
    Cylinder021_5: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshPhysicalMaterial;
    ["Material.009"]: THREE.MeshStandardMaterial;
    glass: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
  };
};

const CAMERA_CONFIG = {
  FOV: 40,
  HEIGHT: 1.5, // Height above the path
  DISTANCE: 8, // Distance from the plane
  INITIAL_POSITION: new THREE.Vector3(0, 1.5, 8),
};

export function Jet(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/realistic_jet.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      {/* Ambient light */}
      <ambientLight intensity={1} />
      {/* Directional light */}
      <directionalLight position={[0, 10, 0]} intensity={1} />
      <group
        position={[0, -1.24, -0.19]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[0.3, 0.3, 0.3]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder021.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder021_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder021_2.geometry}
          material={materials.glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder021_3.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder021_4.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder021_5.geometry}
          material={materials["Material.003"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/realistic_jet.glb");
